name: my_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  # mapbox_gl: ^0.16.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  http: ^1.2.2
  geolocator: ^13.0.2
  url_launcher: ^6.3.1
  dio: ^5.7.0
  flutter_dotenv: ^5.2.1
  flutter_svg: ^2.0.17
  cloud_firestore: ^5.6.1
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.0
  provider: ^6.1.2
  image_picker: ^1.1.2
  file_picker: ^8.3.1
  firebase_storage: ^12.4.2
  path_provider: ^2.1.5
  audioplayers: ^6.1.1
  flutter_sound: ^9.23.1
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  video_player: ^2.3.0 
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/location-arrow-svgrepo-com.svg